spring:
  profiles:
    active: prod

--- # prod 开发环境
spring:
  profiles: prod
  application:
    name: boarding-core
  # mysql
  datasource:
    url: jdbc:mysql://116.62.124.121:3306/boarding
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis.boarding/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8077